### ISSUE TITLE
Lab1: неправильный путь к батнику

### ISSUE THREAD

**Issue by FockinSlave** [MPSU/FPGA_pract#1]
https://github.com/MPSU/FPGA_pract/blame/853e9e466576adacb3134de7f0dcb15fb35ad1bc/Labs/01.%20Tcl/README.md#L58

Правильный путь:
>call D:\Xilinx\Vivado\2023.1\settings64.bat

**Comment by Konf** [comment]
Это зависит от того, какая вивада установлена на машине, по уму путь к `vivado` должен быть вообще в path
Я пока оставлю issue открытым, но это определенно WONTFIX, во всяком случае в предложенном виде
