### ISSUE TITLE
Название сигнала на временной диаграмме

### ISSUE THREAD

**Issue by sorukohi** [MPSU/FPGA_pract#15]
Не должен ли сигнал PWDATA на времянках "pic12.png" и "pic13.png" называться PRDATA, поскольку на них иллюстрируется транзакция чтения из слэйв-устройства?

**Comment by Konf** [comment]
Да, вы совершенно правы. Это на самом деле очень странная ситуация, так как эти времянки явно вырезаны из официальной спецификации APB, и косяк пришёл откуда-то оттуда.

Я могу вас попросить сделать PR, с заменой картинок на корректные из приложенного документа?
[IHI0024D_amba_apb_protocol_spec-1.pdf](https://github.com/MPSU/FPGA_pract/files/15319147/IHI0024D_amba_apb_protocol_spec-1.pdf)

Нужные времянки в разделах 3.3.1 и 3.3.2

**Comment by Konf** [comment]
#25 c правками смержен, issue закрываю
