### ISSUE TITLE
LAB 03. Nets in module mult_dsp_async 

### ISSUE THREAD

**Issue by chistikk** [MPSU/FPGA_pract#5]
В модуле mult_dsp_async объявлены a_i, b_i, а используются a_ff, b_ff

**Comment by Konf** [comment]
Приветствую! Сделайте Pull Request c правкой кода, тогда я со спокойной совестью поставлю бонусные баллы и добавлю вам в соавторы

**Comment by Konf** [comment]
Проблема успешно исправлена в PR #7, поэтому данный issue закрываю
